name: bite
description: "Progetto BITE finanziato nell’ambito dei Bandi a Cascata del Programma NODES, sostenuto dal MUR sui fondi PNRR MUR - M4C2 - Investimento 1.5 Avviso "Ecosistemi dell'Innovazione", nell'ambito del PNRR finanziato dall’Unione europea – NextGenerationEU (Grant agreement Cod. n.ECS00000036)."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.15

  # https://pub.dev/packages/dio
  dio: ^5.7.0

  # Freezed, code generator for data-classes/unions/pattern-matching/cloning.
  # https://pub.dev/packages/freezed
  freezed: ^2.5.7

  # Annotations for freezed.
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4

  # provides a concrete way of generating files using Dart code
  # https://pub.dev/packages/build_runner
  # to run the builder use command:
  #    dart run build_runner build
  build_runner: ^2.4.13

  # Provides Dart Build System builders for handling JSON.
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6

  # https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

  # https://pub.dev/packages/go_router
  go_router: ^14.6.1

  # https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.10.0

  # https://pub.dev/packages/geolocator
  geolocator: ^13.0.2

  # https://pub.dev/packages/logger
  logger: ^2.5.0

  # https://pub.dev/packages/firebase_core
  firebase_core: ^3.8.0

  # https://pub.dev/packages/firebase_remote_config
  firebase_remote_config: ^5.1.5

  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^18.0.1

  # https://pub.dev/packages/flutter_blue_plus
  flutter_blue_plus: ^1.34.5

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.3.3

  # https://pub.dev/packages/firebase_app_installations
  firebase_app_installations: ^0.3.1+7

  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^11.1.1
  flutter_dotenv: ^5.2.1

  # https://pub.dev/packages/dotted_border
  dotted_border: ^2.1.0
  flutter_reactive_ble: ^5.3.1

  # https://pub.dev/packages/image_picker
  image_picker: ^1.1.2

  # https://pub.dev/packages/mime
  mime: ^2.0.0

  # https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1

  #
  infinite_scroll_pagination: ^4.1.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/svg/
    - assets/mock_models/
    - assets/images/
    - assets/images/markers/icon_pin/icon_pin_big.png
    - .env

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
